spring:
  application:
    name: LMS-Spring
  datasource:
    url: jdbc:postgresql://localhost:5432/Spring-LMS
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

